name: Input testing

on:
  workflow_dispatch:
    inputs:
      deploy_enviroment:
        type: choice
        description: Enviroment
        options: 
        - prod
        - dev
        - next
      deploy_version:
        description: 'Deploy Version'     
        required: true
      tags:
        description: 'Build Tags'  

jobs:
  echo_input:
    runs-on: ubuntu-20.04

    steps:
    - name: Echo Env
      run: echo "${{ github.event.inputs.deploy_enviroment }} ${{ github.event.inputs.tags }} ${{ github.event.inputs.deploy_version }}"
    - name: Test Green    
      run: echo -e "Tag is \e[32m${{ github.event.inputs.tags }}\e[0m"
    - name: Test Red
      run: echo -e "Tag is \e[31m${{ github.event.inputs.tags }}\e[0m"
    - name: Test Blue
      run: echo -e "Tag is \e[34m${{ github.event.inputs.tags }}\e[0m"
    - name: Test Purple
      run: echo -e "Tag is \e[35m${{ github.event.inputs.tags }}\e[0m"
