name: Input testing

on:
  workflow_dispatch:
    inputs:
      deploy_enviroment:
        type: choice
        description: Enviroment
        options: 
        - prod
        - dev
        - next
      deploy_version:
        description: 'Deploy Version'     
        required: true
      tags:
        description: 'Build Tags'  

jobs:
  echo_input:
    runs-on: ubuntu-20.04

    steps:
    - name: Echo Env
      run: echo "${{ github.event.inputs.deploy_enviroment }} ${{ github.event.inputs.tags }} ${{ github.event.inputs.deploy_version }}"
    - name: Test Colours
      run: echo -e "${Red}*** ${Green}${{ github.event.inputs.tags }}"
